name: Publish to GitHub Packages (Prerelease)
# tags like: v1.2.3-rc.1
on:
  release:
    types: [prereleased] # trigger on prereleases
  workflow_dispatch:

permissions:
  contents: write # (optional) needed if you attach assets to the GitHub Release
  packages: write # required to publish to GitHub Packages

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.x
            8.x
            7.x

      - name: Compute version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF_NAME}"
          VERSION="${TAG#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Restore
        run: dotnet restore

      - name: Build Release (skip net472;net48 for ubuntu)
        run: dotnet build --configuration Release --no-restore -p:TargetFrameworks="netstandard2.1;net7.0;net8.0;net9.0"

      - name: Pack
        run: |
          dotnet pack ZLab.Discrete/ZLab.Discrete.csproj \
            --configuration Release \
            --no-build \
            -p:TargetFrameworks="netstandard2.1;net7.0;net8.0;net9.0" \
            -p:PackageVersion=${VERSION} \
            -p:Version=${VERSION} \
            -p:ContinuousIntegrationBuild=true \
            -p:IncludeSymbols=true \
            -p:SymbolPackageFormat=snupkg \
            -p:RepositoryUrl=${{ github.server_url }}/${{ github.repository }} \
            -p:RepositoryCommit=${{ github.sha }} \
            --output ./nupkgs

      - name: Add GitHub Packages source
        run: |
          dotnet nuget add source \
            "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --name "github" \
            --username "${{ github.actor }}" \
            --password "${{ secrets.GITHUB_TOKEN }}" \
            --store-password-in-clear-text

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --source "github" \
            --skip-duplicate
          dotnet nuget push "./nupkgs/*.snupkg" \
            --source "github" \
            --skip-duplicate

      # Optional: attach artifacts to the prerelease for convenience
      - name: Attach packages to the GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            nupkgs/*.nupkg
            nupkgs/*.snupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
