name: Publish (GitHub Packages + NuGet.org)

on:
  release:
    types: [published] # trigger on published releases (not prereleases)
  workflow_dispatch: # allow manual triggering

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.x
            8.x
            7.x
          cache: true # enable caching
          cache-dependency-path: |
            **/*.csproj
            **/Directory.Packages.props
            **/packages.lock.json
            global.json
            nuget.config

      - name: Compute version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF_NAME}"
          VERSION="${TAG#v}"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Restore
        run: dotnet restore

      - name: Build Release
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: |
          dotnet pack ZLab.Discrete/ZLab.Discrete.csproj \
            --configuration Release \
            --no-build \
            -p:PackageVersion="$VERSION" \
            -p:Version="$VERSION" \
            -p:ContinuousIntegrationBuild=true \
            -p:IncludeSymbols=true \
            -p:SymbolPackageFormat=snupkg \
            -p:RepositoryUrl=${{ github.server_url }}/${{ github.repository }} \
            -p:RepositoryCommit=${{ github.sha }} \
            --output ./nupkgs

      - name: Add GitHub Packages source
        run: |
          dotnet nuget add source \
            "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --name "github" \
            --username "${{ github.actor }}" \
            --password "${{ secrets.GITHUB_TOKEN }}" \
            --store-password-in-clear-text

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" --source "github" --skip-duplicate
          dotnet nuget push "./nupkgs/*.snupkg" --source "github" --skip-duplicate

      - name: Publish to NuGet.org
        if: ${{ github.event.release.prerelease == false }}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --api-key "$NUGET_API_KEY" \
            --source "https://api.nuget.org/v3/index.json" \
            --skip-duplicate
          dotnet nuget push "./nupkgs/*.snupkg" \
            --api-key "$NUGET_API_KEY" \
            --source "https://api.nuget.org/v3/index.json" \
            --skip-duplicate

      - name: Attach packages to the GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            nupkgs/*.nupkg
            nupkgs/*.snupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
