name: Publish to GitHub Packages

on:
  release:
    types: [published] # trigger when a release is published

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # for versioning tools that look at git history

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Add GitHub Packages as NuGet source
      run: |
        dotnet nuget add source \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github \
          https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    - name: Pack library
      run: |
        dotnet pack Zlab.Discrete/ZLab.Discrete.csproj \
          --configuration Release \
          --output ./nupkgs

    - name: Publish package to GitHub Packages
      run: |
        dotnet nuget push ./nupkgs/*.nupkg \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source github \
          --skip-duplicate
