name: Publish to GitHub Packages + NuGet.org

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write     # upload assets to the release
  packages: write     # publish to GitHub Packages (GPR)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            7.x

      - name: Compute version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF_NAME}"
          VERSION="${TAG#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: |
          dotnet pack Zlab.Discrete/ZLab.Discrete.csproj \
            --configuration Release \
            --no-build \
            -p:PackageVersion=${VERSION} \
            -p:Version=${VERSION} \
            -p:ContinuousIntegrationBuild=true \
            -p:IncludeSymbols=true \
            -p:SymbolPackageFormat=snupkg \
            -p:RepositoryUrl=${{ github.server_url }}/${{ github.repository }} \
            -p:RepositoryCommit=${{ github.sha }} \
            --output ./nupkgs

      # ---------- GitHub Packages ----------
      - name: Add GitHub Packages source
        run: |
          dotnet nuget add source \
            "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --name "github" \
            --username "${{ github.actor }}" \
            --password "${{ secrets.GITHUB_TOKEN }}" \
            --store-password-in-clear-text

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --source "github" \
            --skip-duplicate
          dotnet nuget push "./nupkgs/*.snupkg" \
            --source "github" \
            --skip-duplicate

      # ---------- NuGet.org ----------
      - name: Publish to NuGet.org
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --source "https://api.nuget.org/v3/index.json" \
            --skip-duplicate
          dotnet nuget push "./nupkgs/*.snupkg" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --source "https://api.nuget.org/v3/index.json" \
            --skip-duplicate

      - name: Attach packages to the GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            nupkgs/*.nupkg
            nupkgs/*.snupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
